# Generated by Django 5.2.6 on 2026-10-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin', models.CharField(max_length=30)),
                ('ape_admin', models.CharField(max_length=30)),
                ('usuario_admin', models.CharField(max_length=30)),
                ('email_admin', models.CharField(max_length=50)),
                ('contrasena_admin', models.CharField(max_length=30)),
                ('fecha_nacimiento_admin', models.DateField()),
                ('direccion_admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='automovil',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_automovil', models.CharField(max_length=30)),
                ('descripcion_automovil', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='autos/')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('ape_cliente', models.CharField(max_length=30)),
                ('email_cliente', models.CharField(max_length=50)),
                ('contrasena_cliente', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_cliente', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.CharField(max_length=30)),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.automovil')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.cliente')),
            ],
        ),
    ]
